### ISSUE TITLE
Bluez5 ?

### ISSUE THREAD

**Issue by lunarok** [Phhere/Playbulb#6]
Hi,

Did you manage to get this working with Bluez5 ? gattool is giving me hard time. Everything working fine with 4, but now Jessie is under Bluez 5 and Ubuntu Wily too, hard time

**Comment by lunarok** [comment]
OK, with debian Jessie it's working so no problem for me.
But really strange thèse problèms with gatttool.

Whatever I have an issue with one type of bulb, I think it's a rainbow. I will post on thé rainbow issue (candles and garden are OK)

**Comment by idem2lyon** [comment]
Hi Lunarok,
As I said, with a fresh Jessie, updated, and with clean bluez install (apt), it doesn't work.
With a fresh Jessie, updated, and with compiled bluez (5.35), it doesn't work anymore.

Can you give more please? :)

Merci copain :)
----8<-------------------
root@jarvis:/opt/scripts/install/bluez-5.35# cat /etc/debian_version 
8.0

root@jarvis:/opt/scripts/install/bluez-5.35/attrib# hcitool lescan
LE Scan ...
75:E9:4B:0B:AC:E6 Sarah
75:E9:4B:0B:AC:E6 (unknown)
3A:21:4B:0B:AC:E6 Mehdi
3A:21:4B:0B:AC:E6 (unknown)
3A:10:4B:0B:AC:E6 (unknown)
3A:10:4B:0B:AC:E6 Temperature
DB:11:5E:15:42:B5 X6-E525
DB:11:5E:15:42:B5 (unknown)
^C

root@jarvis:/opt/scripts/install/bluez-5.35/attrib#  gatttool -b 3A:10:4B:0B:AC:E6 --interactive
[3A:10:4B:0B:AC:E6][LE]> connect
Attempting to connect to 3A:10:4B:0B:AC:E6
Error: connect: Connection refused (111)
----8<-------------------

or

----8<-------------------
root@jarvis:/opt/scripts/install/Playbulb-master# hciconfig
hci0:   Type: BR/EDR  Bus: USB
        BD Address: 5C:F3:70:6C:73:88  ACL MTU: 1021:8  SCO MTU: 64:1
        UP RUNNING 
        RX bytes:2583 acl:0 sco:0 events:131 errors:0
        TX bytes:926 acl:0 sco:0 commands:85 errors:0

root@jarvis:/opt/scripts/install/Playbulb-master# hciconfig hci0 up
root@jarvis:/opt/scripts/install/Playbulb-master# hcitool lescan
LE Scan ...
3A:21:4B:0B:AC:E6 Mehdi
3A:21:4B:0B:AC:E6 (unknown)
75:E9:4B:0B:AC:E6 Sarah
75:E9:4B:0B:AC:E6 (unknown)
3A:10:4B:0B:AC:E6 (unknown)
3A:10:4B:0B:AC:E6 Temperature
DB:11:5E:15:42:B5 X6-E525
DB:11:5E:15:42:B5 (unknown)
^C

root@jarvis:/opt/scripts/install/Playbulb-master# gatttool -b 3A:10:4B:0B:AC:E6 --char-write -a 0x0016 -n 0000ff00  
connect: Connection refused (111)
----8<-------------------
