### ISSUE TITLE
Trouble connecting to Playbulb Rainbow

### ISSUE THREAD

**Issue by spencerhooks** [Phhere/Playbulb#7]
I'm having trouble connecting to a Playbulb Rainbow and am hoping someone might be able to help - not really sure who else to ask.

I can see the device with hcitool lescan, but when I try to connect with gatttool I get "connect error: Host is down (112)". I get this either connecting interactively or just sending a command.

I also tried updating Bluez to the latest version, but then I get a connection refused error. This error comes back so quickly that I'm not sure it's actually trying to connect.

I tried reseting the bulb to factory, which seemed to work because the name changed. But other than that I'm not sure what to try.

Any suggestions would be greatly appreciated. Thanks very much!

**Comment by derchrisuk** [comment]
What OS is this, and what version of it and BlueZ are you using?

**Comment by spencerhooks** [comment]
Thanks for the reply. I tried a fresh install of Raspbian Jessie and Buez 5.23 (just did an apt-get install bluez). Now it's working! Thanks for figuring this out.
